### ISSUE TITLE
Set component props doesn't allow set the color

### ISSUE THREAD

**Issue by jesustorresdev** [stnrd/healthicons#11]
The documentation explain that it is possible to change standard SVG properties:

https://github.com/stnrd/healthicons/tree/main/packages/healthicons-react

That is true, but set color or fill doesn't change the icon color. That is because the path element inside the SVG already contains a fill attribute set to "#000". I have had to use styled components to overwrite that property.

**Comment by stnrd** [comment]
Good catch I have merged an MR which removes the fill attribute from the inner paths. (https://github.com/stnrd/healthicons/pull/12).

I will trigger a release right now.

**Comment by stnrd** [comment]
Release v1.5.0 should solve this issue, let me know if you still have issues 👍

**Comment by jesustorresdev** [comment]
Thank you. Now, I can change the icon colors.

The only problem I see now is the icons aren't drawn by default, unless I set the fill property.
Maybe, it should have a default value, like "currentColor", that is the default value for color property.

**Comment by stnrd** [comment]
I will have a look into the default color and do some experimenting. I am working on including some example react and native applications in the repo this makes testing a bit easier.

**Comment by sten-nico** [comment]
I have added currentColor to fill as a default. I want to double check if this doesn't break the contextProvider otherwise I can create a new release.
