### ISSUE TITLE
import *

### ISSUE THREAD

**Issue by kristiandupont** [stnrd/healthicons#13]
Thank you for doing this!
I would like to allow my users to search for an icon in the UI. This means that I would like to import the metadata that you provide, as well as every single icon, so they are readily available. Is this possible today in a way that I am just missing?

**Comment by jesustorresdev** [comment]
Hi,

Are you talking about use the tags in for the search?

https://github.com/stnrd/healthicons/blob/main/icons/meta-data.json

I'm trying to do the same thing, but I didn't find any file in the repo where the relationship between icon name and component name is stored. Yesterday, I made a script trying to match component and icon name and store them in my app, but I found some components are missing (see #15)

If that information could be generated during the build of these packages, it would be amazing.

**Comment by kristiandupont** [comment]
Yes, that is what I meant :-)

**Comment by sten-nico** [comment]
Hi all, 

I can generate such a file during the build process that links an icon name with a React component, if that is what is desired. I do have some questions: How should I expose such file? Should I include it in the packages or is on root level fine?  

About  the missing icons I have fixed them in this PR #16.

**Comment by kristiandupont** [comment]
Awesome, thanks! I can only speak for myself here, but either would work for me. I guess if it's a part of the package, that would make things slightly more streamlined.

**Comment by stnrd** [comment]
Sorry it took a while but I have done a big refactoring related on how I build the icons and how you can import them. At the moment I don't like the way import work and VSCode isn't picking up the icons automatically without importing at least one icon. 

I have created an [MR](https://github.com/stnrd/healthicons/pull/18) that changes the way to import from `import healthicons-react/dist/filled` to just  `import healthicons-react`. The default variant on the root level is `filled`, but this can be easily changed by doing `healthicons-react/outline`. I am going to release this a 2.0.0 version as it breaks the current way of importing. 

To make the link between an React component and a Healthicons ID, I have included an `updated-meta-data.json` file in all the React packages. Example of an entry in the metadata file
```
{
    "id": "war",
    "category": "vehicles",
    "path": "vehicles/war",
    "tags": [
      "Armored Vehicle",
      "Cannon",
      "Gun",
      "Military",
      "Tank",
      "dhis2:war"
    ],
    "title": "Tank",
    "component_name": "War" <------ React component name
  },
```

This file can be easily imported directly out the `import metadata from '../node_modules/healthicons-react/updated-meta-data.json';` package, see the attached `examples/next` where I am doing that and created a simple icon search. 

![image](https://github.com/stnrd/healthicons/assets/66428392/0dd0b96e-b703-4f13-8c03-216ed1fb8cf7)

**Comment by kristiandupont** [comment]
That's awesome, thank you!
