### ISSUE TITLE
Name of '!' icon should be ExclamationMark not ExplanationMark

### ISSUE THREAD

**Issue by jesustorresdev** [stnrd/healthicons#14]
I found the name for exclamation mark icon is ExplanationMark. I guess it is a typo.
It is set as explanation-mark in:

https://github.com/stnrd/healthicons/blob/main/constants.js

**Comment by sten-nico** [comment]
Solved in #16

**Comment by stnrd** [comment]
Create a new release (1.6.0) which solves all the issues of missing icons, typos and currentColor missing

**Comment by jesustorresdev** [comment]
Thank you.
